export default {
  REAPPLY_COOLDOWN_HOURS: parseInt(process.env.REAPPLY_COOLDOWN_HOURS || '24'),
  EXTRA_COOLDOWN_HOURS: parseInt(process.env.EXTRA_COOLDOWN_HOURS || '24'),
  REJECTION_HISTORY_WINDOW_HOURS: parseInt(process.env.REJECTION_HISTORY_WINDOW_HOURS || '168'),
  REJECTIONS_BEFORE_EXTRA_COOLDOWN: parseInt(process.env.REJECTIONS_BEFORE_EXTRA_COOLDOWN || '3'),
  ADMIN_REAPPLY_COOLDOWN_DAYS: parseInt(process.env.ADMIN_REAPPLY_COOLDOWN_DAYS || '7'),
  UNBAN_COOLDOWN_PERCENT: parseFloat(process.env.UNBAN_COOLDOWN_PERCENT || '0.15')
};
