export default {
  REAPPLY_COOLDOWN_HOURS: parseInt(process.env.REAPPLY_COOLDOWN_HOURS || '24'),
  EXTRA_COOLDOWN_HOURS: parseInt(process.env.EXTRA_COOLDOWN_HOURS || '24'),
  REJECTION_HISTORY_WINDOW_HOURS: parseInt(process.env.REJECTION_HISTORY_WINDOW_HOURS || '168'),
  REJECTIONS_BEFORE_EXTRA_COOLDOWN: parseInt(process.env.REJECTIONS_BEFORE_EXTRA_COOLDOWN || '3')
};
