export default {
  "REAPPLY_COOLDOWN_HOURS": 0,
  "EXTRA_COOLDOWN_HOURS": 24,
  "REJECTION_HISTORY_WINDOW_HOURS": 168,
  "REJECTIONS_BEFORE_EXTRA_COOLDOWN": 3,
  "ADMIN_REAPPLY_COOLDOWN_DAYS": 7,
  "UNBAN_COOLDOWN_PERCENT": 0.15,
  "QUESTIONS": {
    "whitelist": [
      "Co zrobisz, jeśli zobaczysz gracza łamiącego zasady roleplayu (np. powergaming)?",
      "Jak zareagujesz, gdy Twój znajomy z OOC przekaże Ci informacje IC?",
      "Podaj przykład, jak prawidłowo użyć komendy /me w sytuacji przeszukania.",
      "Co wpiszesz w /do, gdy Twoja postać zostaje zatrzymana do kontroli przez policję?",
      "Twoja postać została postrzelona – jak odgrywasz taką sytuację IC?",
      "Co oznacza skrót NVL i jak rozumiesz jego zastosowanie?",
      "Gracz ucieka z miejsca zdarzenia po wypadku – jak powinieneś się zachować jako świadek?",
      "Jak wygląda różnica między IC a OOC i dlaczego ważne jest ich oddzielenie?",
      "Kto podejmuje decyzję w sytuacji konfliktowej – IC czy administracja OOC?",
      "Czy Twoja postać może wiedzieć, kto ją zabił, jeśli została zastrzelona z zaskoczenia? Uzasadnij.",
      "Gracz używa voice chatu, by przekazać coś spoza gry – jak powinieneś zareagować?",
      "Czy możesz napisać na czacie OOC \"dlaczego mnie zabiłeś?\"? Jeśli nie, to gdzie to zgłosić?",
      "Twoja postać traci przytomność – jakie działania podejmujesz jako gracz?",
      "Podaj przykład zachowania, które uznajesz za powergaming.",
      "Czy Twoja postać może znać lokalizację kogoś, kogo nie widziała od kilku dni? Wyjaśnij.",
      "Masz 3 osoby celujące do Ciebie z broni – co robisz i jak to odgrywasz?",
      "Czy możesz zmienić postać i kontynuować zemstę na kimś, kto zabił Twoją poprzednią? (nawiązanie do new life rule)",
      "Jakie są konsekwencje odgrywania scen, które są niezgodne z lore/realizmem serwera?",
      "Podaj przykład poprawnego odgrywania sceny handlu narkotykami.",
      "Czy masz obowiązek zapisać swoją postać po śmierci permanentnej? Co to oznacza?",
      "Czy Twoja postać może mieć wspomnienia po śmierci permanentnej?",
      "Jakie znasz zasady związane z porwaniami innych graczy?",
      "Czy można napaść na LSPD bez zaplanowanej akcji IC? Dlaczego tak/nie?",
      "Czy można wjechać na teren frakcji bez uzasadnienia IC?",
      "Podaj przykład metagamingu w rozmowie głosowej.",
      "Czy Twoja postać może wiedzieć, że ktoś handluje narkotykami, jeśli nikt jej tego nie powiedział IC?",
      "W jaki sposób zgłaszasz łamanie zasad, jeśli nie chcesz eskalować konfliktu?",
      "Podczas RP ktoś używa obraźliwego języka OOC – co robisz?",
      "Twoja postać jest świadkiem napadu – czy możesz to od razu zgłosić IC? Jak?",
      "Czy Twoja postać może znać cenę broni, jeśli nie była w sklepie IC?",
      "Podaj przykład łamania zasady Fail RP.",
      "Co oznacza skrót VDM?",
      "Czy Twoja postać może rozpoznać kogoś tylko po ubraniu i masce?",
      "Czy odgrywanie choroby psychicznej wymaga zgody administracji?",
      "Jakie zachowania są niedozwolone w scenach z udziałem medyków?",
      "Czy możesz rozłączyć się z gry w trakcie aresztowania? Co jeśli to przypadek?",
      "Masz 2 postacie – czy mogą się znać lub współpracować?",
      "Jakich działań nie wolno podejmować, by uniknąć konsekwencji IC?",
      "Czy możesz przywrócić swoją postać po permie, jeśli „umarła przypadkiem”?",
      "Co robisz, jeśli przez przypadek złamiesz zasadę, np. przypadkowy metagaming?",
      "Podaj przykład dobrze rozegranego napadu IC.",
      "W jaki sposób Twoja postać może poznać członka gangu?",
      "Czy możesz przeprowadzić transakcję bronią przy komendzie LSPD?",
      "Jak należy odgrywać użycie broni palnej w miejscu publicznym?",
      "Czy zemsta OOC na kimś IC jest dozwolona?",
      "Czy można stosować szantaż OOC? Jeśli nie – co robić, gdy się to zdarzy?",
      "Twoja postać została pobita, ale nie zgłosiła tego – czy może później się mścić IC?",
      "Czy każda postać musi mieć unikalną historię? Dlaczego?",
      "Jaki wpływ ma realność RP na immersję graczy?",
      "Czy możesz prowadzić grupę przestępczą bez zgody administracji?"
    ],
    "checker": [],
    "moderator": [
      "Ktoś pisze na publicznym czacie: „admin to idiota”.",
      "Gracz spamuje memami w poważnej dyskusji mimo ostrzeżeń.",
      "Ktoś wstawia wulgarną nazwę użytkownika i pisze nią na czacie.",
      "Gracz podaje link do innego serwera Discord.",
      "Rozpoczyna się kłótnia między dwiema frakcjami — Discord płonie.",
      "Gracz prowokuje pytaniami typu „ile macie IQ?” wśród innych.",
      "Ktoś zgłasza rasistowski lub homofobiczny komentarz — nie ma screena.",
      "Gracz pisze do Ciebie na DM z groźbą zgłoszenia do właściciela.",
      "W ticketach ktoś pisze same „XD” i „lol” — nie wiadomo o co chodzi.",
      "Grupa graczy spamuje jednocześnie w kilku kanałach (np. @everyone, .gif).",
      "Ktoś zgłasza oszustwo IC na czacie OOC — temat eskaluje.",
      "Gracz oznacza właściciela bez powodu, mimo ostrzeżeń.",
      "Ktoś publikuje screen z prywatnej rozmowy z innym graczem.",
      "Gracz celowo psuje zgłoszenia — usuwa wiadomości, edytuje odpowiedzi.",
      "Ktoś przesyła zdjęcie kontrowersyjnego contentu NSFW (mimo zakazu).",
      "Zgłoszenie „moderator nie reaguje, więc piszę tu!” — co robisz?",
      "Na kanale IC ktoś zaczyna pisać czystym OOC-em i robi burdel.",
      "Gracz trolluje tickety pisząc o „duchach w systemie” – nic konkretnego.",
      "Współpracownik z ekipy odpowiada z ironią do gracza — co robisz?",
      "Ktoś pisze „to nie złamanie regulaminu, ale zachował się jak frajer” — co robisz?"
    ],
    "administrator": [
      "Gracze zgłaszają, że jedna frakcja dominuje wszystkie inne – jak reagujesz?",
      "System whitelist się zapchał – 50 podań w 1 dzień, tylko 2 osoby do sprawdzania.",
      "Trzy osoby z ekipy pokłóciły się w kanale prywatnym – co robisz?",
      "W środku nocy padła baza danych – Owner śpi, Dev niedostępny.",
      "Ktoś zmienia handlingi bez zgody – jak dojść kto, i co robisz?",
      "Gracze oskarżają frakcję o metagaming – zgłoszenie na kanale publicznym.",
      "Serwer dostał raida na Discordzie – co robisz przez pierwsze 5 minut?",
      "Tester zgłasza błąd krytyczny na produkcji – jak organizujesz reakcję?",
      "W evencie bierze udział 50 osób, event się wysypuje – kto odpowiada?",
      "CM nie odpowiada na ważny temat, mod wchodzi w jego miejsce – co robisz?",
      "Developer wypuścił niedziałający skrypt i nie odbiera wiadomości.",
      "Nowy admin zaczyna wprowadzać zmiany bez ustaleń – jak reagujesz?",
      "Dwie frakcje chcą tę samą lokalizację – jak rozwiązać sprawę?",
      "Masz za mało adminów – kogo szukasz, jak oceniasz kandydata?",
      "WLChecker nagle rezygnuje i zostawia nieprzeczytane 60 podań.",
      "W grze pojawiły się „dzikie pojazdy” spoza listy – jak to zabezpieczasz?",
      "Kanał z logami przestał działać – co robisz jako pierwsze?",
      "CM prowadzi event, ale gracze go wyśmiewają – jak pomagasz?",
      "Zgłasza się osoba z inną rangą, że nie chce pracować z danym Developerem.",
      "Gracze IC wynoszą OOC dramy – jak jako admin reagujesz?"
    ],
    "developer": []
  }
}
